# Generated by Django 4.0.1 on 2023-08-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='geolocation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
