# Generated by Django 4.0.1 on 2023-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(default=178),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(default=63),
            preserve_default=False,
        ),
    ]
