# Generated by Django 4.2 on 2023-04-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diseases', models.ManyToManyField(related_name='symptoms', to='diseases.diseases')),
            ],
        ),
    ]
