# Generated by Django 4.2 on 2023-04-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_disease_symptom_remove_symptoms_diseases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='symptom',
            new_name='symptoms',
        ),
    ]
