# Generated by Django 4.0.1 on 2023-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_alter_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='additional_resources',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='disease',
            name='prognosis_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatement',
            field=models.TextField(default=''),
        ),
    ]
