# Generated by Django 4.0.1 on 2023-08-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_disease_additional_resources_disease_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='additional_resources',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(default='1', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='diseases.specialization'),
            preserve_default=False,
        ),
    ]
