# Generated by Django 4.0.1 on 2023-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_remove_doctor_distance_to_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
